### PR TITLE
update of components

### PR DESCRIPTION
**Pull request by smiklosovic**
@timyates 

could you please have a look?

Two tests are failing, it seems it fails randomly. I bet they are some synchronization issues.

merge and release would be awesome.

### CODE REVIEW

**Comment by timyates** [comment]
Cool, cheers.

Will look as soon as I get to a computer :-)

**Comment by smiklosovic** [comment]
http://pastebin.com/qYH1jLrP

**Comment by timyates** [comment]
Went up to 0.9.5 for c3p0, the idle connection exception seems to go away ;-)

**Comment by timyates** [comment]
Thanks!

**Comment by smiklosovic** [comment]
@timyates would you please release it to module repository and to maven central so i can pull this dependency to my module?

**Comment by timyates** [comment]
It should be in maven

**Comment by timyates** [comment]
http://search.maven.org/#artifactdetails%7Ccom.bloidonia%7Cmod-jdbc-persistor%7C2.1.4%7Cjar

**Comment by timyates** [comment]
Just filled in the form for the module registry as well, so that should
update once someone accepts it

**Comment by smiklosovic** [comment]
@timyates thanks! i tried it and so far it works like a breeze! in case of any issues, i'll keep you posted.

**Pull request merged**
